# Data Storage in OpenPNM

OpenPNM uses 2 very common python data structures, so it's best to get comfortable with them right away.  In this example we'll cover:

1. Python's ``list``
1. Numpy's ``ndarray``
1. Python's `dict` or *dictionary*
1. OpenPNM's naming convention
1. Data vs Labels in OpenPNM

## Python Lists: Flexible but Slow
First lets quickly look at Python's *array*, which is called a ``list``.  It is indicated by the square brackets:

In [33]:
L = [0, 2, 4, 6, 8]

You can read and write values as follows:

In [34]:
L[0] = L[2]*L[4]
print(L)

[32, 2, 4, 6, 8]


Note that Python uses 0-indexing, and also that square brackets are used to index into any sequence.

You can make the ``list`` longer, and remove items:

In [40]:
L.append(100)
print(L)

[32, 2, 6, 8, 100, 100]


In [41]:
L.pop(2)
print(L)

[32, 2, 8, 100, 100]


However, this list is not very good at math:

In [42]:
try:
    print(L + 2)
except TypeError:
    print('Adding to a list assumes you are joining 2 lists')
print(L + [2, 3])

Adding to a list assumes you are joining 2 lists
[32, 2, 8, 100, 100, 2, 3]


And multiplication assumes you want to duplicate the list N times:

In [43]:
print(L*2)

[32, 2, 8, 100, 100, 32, 2, 8, 100, 100]


The reason the list is not ideal for numerical operations is that *anything* can be stored in each element:

In [44]:
L[0] = 'str'
print(L)

['str', 2, 8, 100, 100]


This is why it's not possible to add or multiply a list, since Python does not necessarily know the meaning of adding an integer and a string (i.e. 'str' + 1).

## Numpy ``ndarray``: Optimized for Numerics
Now let's take a look at the Numpy ``ndarray``. Numpy is used *very* extensively in scientific python because the native `list` discussed above is not very fast. Numpy arrays on the other hand are actually "C" arrays behind the scenes so are very fast. The downside is that you must learn a 'mini-language' to use them.  The following few code blocks illustrate this.  

In [16]:
import numpy as np
a = np.arange(0, 100, 15)
print(a)

[ 0 15 30 45 60 75 90]


In [17]:
print(a[2])

30


In [18]:
a[0] = 999
print(a)

[999  15  30  45  60  75  90]


You can also choose a subset of indices:

In [19]:
print(a[[0, 2, 4]])

[999  30  60]


You can set multiple locations with a single value:

In [22]:
a[[0, 2, 4]] = -100
print(a)

[-100   15 -100   45 -100   75   90]


Or an array of values:

In [23]:
a[[1, 3, 5]] = [111, 222, 333]
print(a)

[-100  111 -100  222 -100  333   90]


And of course, math makes sense to an ``ndarray`` since *all* the elements are assured to be numbers:

In [45]:
print(a*2)

[-200  222 -200  444 -200  666  180]


In [46]:
print(a + 100)

[  0 211   0 322   0 433 190]


In [47]:
print(a*a)

[ 10000  12321  10000  49284  10000 110889   8100]


## Dictionaries: Holding Things Together
The last piece of the puzzle is Python's built-in ``dict``.  This allow one to store *anything* by name in a single container:

In [51]:
d = dict()
d['arr'] = a
d['list'] = L
print(d)

{'arr': array([-100,  111, -100,  222, -100,  333,   90]), 'list': ['str', 2, 8, 100, 100]}


You can retrieve any element by name:

In [52]:
print(d['arr'])

[-100  111 -100  222 -100  333   90]


And adding new items is easy:

In [55]:
d['test'] = 1.0
print(d)

{'arr': array([-100,  111, -100,  222, -100,  333,   90]), 'list': ['str', 2, 8, 100, 100], 'test': 1.0}


Like lists, ``dict``s can hold anything in each element, including arrays, lists or even other ``dict``s.